# Generated by Django 4.0.5 on 2022-08-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_sponsored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
